### ISSUE TITLE
how to monitor health of the dashboard?

### ISSUE THREAD

**Issue by maelle** [r-hub/cransays#12]
do we want to get notified if the table has 0 row?

**Comment by Bisaloo** [comment]
A related topic (but maybe not exactly what you are getting at here): GitHub Actions have this annoying behaviour where only the person that created the action will be notified of failures when an action runs on a schedule.

To deal with this, I've added a final step to some of my repos to open an issue when a scheduled workflow fails. Is this something we want here?
Alternatively, it could be a single issue that we close & reopen (automatically) to avoid creating many issues if the workflow is flaky.

**Comment by maelle** [comment]
> Alternatively, it could be a single issue that we close & reopen (automatically) to avoid creating many issues if the workflow is flaky.

This sounds smart

**Comment by llrs** [comment]
In my experience it has never been 0 (even on holidays or maintenance periods) packages/files on the queue. 
More often it was not working or saving the reports so this issue-openeing setup can be helpful to reactivate or fix the action.

**Comment by Bisaloo** [comment]
I need to revisit this because it's a problem that the last step depends on R & R packages (gh). If the step to install R or the package fails (like today, or because RSPM/CRAN have some issues), then the step to re-open the issue will fail as well.

We need a zero dependency solution, i.e., using curl directly to interact with GitHub API.
