### ISSUE TITLE
Description for `pending` is wrong?

### ISSUE THREAD

**Issue by Bisaloo** [r-hub/cransays#29]
On the dashboard, it is written:

>  pending: the CRAN maintainers are waiting for an action on your side. You should check your emails!

Yet, for the lightr package, which is currently in `pending`, I got the following email:

> Dear maintainer,
 >
> package lightr_1.2.tar.gz has been auto-processed and is pending a manual inspection. A CRAN team member will typically respond to you within the next 5 working days. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

**Comment by Bisaloo** [comment]
For context, I got an unexpected `NOTE`:

>   Found the following (possibly) invalid URLs:
    URL: https://codecov.io/github/ropensci/lightr?branch=master
      From: README.md
      Status: Error
      Message: libcurl error code 35:
        	schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).

My guess is that this creates a lot of false positives and it is double checked by a human from the CRAN team.

**Comment by maelle** [comment]
interesting, thanks, should we add a sentence to the pending description? Wanna make a PR?

**Comment by maelle** [comment]
@Bisaloo re-looking at your issue after seeing https://stat.ethz.ch/pipermail/r-package-devel/2020q4/006153.html

I wonder what the description should be for pending. Saying that no action is required from the maintainer? :thinking: 

Things sure changed since https://journal.r-project.org/archive/2018-1/cran.pdf

**Comment by Bisaloo** [comment]
Yes, I answered to the list linking to the source (R journal) and this issue but my message is awaiting moderation.

It is indeed becoming apparent things have changed but the problem is that we don't have any official information about the current meaning of `pending`. I was hoping the [latest issue of the R journal](https://journal.r-project.org/archive/2020-1/cran.pdf) would clarify this but they don't mention this at all.

The proposed explanation in the mailing list seems reasonable ("'pending' means CRAN is pondering the state of the package") but it's a guess as well.

**Comment by bbolker** [comment]
This was clarified by Uwe Ligges in 2019:

https://stat.ethz.ch/pipermail/r-package-devel/2019q1/003631.html

> pending means a team member has to do a closer inspection and needs more 
time while waiting means user reactions, this is a recent change since 
we wrote the publication you cited.

Shall I make a PR?

Evidence of confusion:

- https://stat.ethz.ch/pipermail/r-package-devel/2020q4/006151.html
- https://stat.ethz.ch/pipermail/r-package-devel/2022q2/008082.html

**Comment by Bisaloo** [comment]
@bbolker, good catch and thanks for the information. A PR would be welcome!

**Comment by Bisaloo** [comment]
Fixed by #60.
