### ISSUE TITLE
Only include tar.gz files

### ISSUE THREAD

**Issue by Bisaloo** [r-hub/cransays#30]
It looks like someone inadvertently added a pdf in their folder:

![image](https://user-images.githubusercontent.com/10783929/92162932-364d4d80-ee33-11ea-8960-b790da18adf6.png)

To prevent this, it would be useful to ensure only `tar.gz` are listed. I can submit a PR for this in the next couple of days if necessary.

**Comment by Bisaloo** [comment]
Oh wait, this is supposed to already be the case:

https://github.com/lockedata/cransays/blob/f80133d3dbc8e2064c4c49ef66291b0ca721779a/R/take-snapshot.R#L41

:thinking:

**Comment by maelle** [comment]
weird, and good catch! I won't have time to dive into it myself during the next few days, so if you have time to explore that'd be great (no worries if not, of course).

**Comment by maelle** [comment]
Or maybe it's just a really weird case that we should ignore? See screenshot below, the file extension is dot pdf dot tar dot gz.

![image](https://user-images.githubusercontent.com/8360597/92223497-d4c3c800-eea0-11ea-9faa-b82ec2ba3288.png)

**Comment by Bisaloo** [comment]
Oh right... Really strange indeed. And quite impossible to detect in this case :thinking:

**Comment by maelle** [comment]
I am so curious now, why did this end up there?!

**Comment by maelle** [comment]
@Nowosad how did a PDF of your book (or at least a file named like your book) end up in CRAN incoming FTP? :slightly_smiling_face: ftp://cran.r-project.org/incoming/

**Comment by Nowosad** [comment]
Hi @maelle - good question. Long story short: I have tried to submit my textbook in Polish to the CRAN Contributed Documentation (https://cran.r-project.org/other-docs.html#nenglish). 

However, the instruction on how to do that are vague.
The Contributed Documentation page states "To submit, follow the submission instructions on the CRAN main page.", however, it is impossible to upload non-R package using the standard way (https://cran.r-project.org/submit.html). Therefore, I decided to follow another CRAN suggestion "If this fails, upload to ftp://CRAN.R-project.org/incoming/ and send an email to CRAN-submissions@R-project.org following the policy. Please do not attach submissions to emails, because this will clutter up the mailboxes of half a dozen people." and uploaded the PDF to CRAN incoming FTP and wrote an email. Yet, I still did not get any answers back...

Do you know any better way how to add a document to the CRAN Contributed Documentation?

**Comment by maelle** [comment]
:wave: @Nowosad, that's interesting and no, sorry, I don't know how to do that. Maybe you could email r-package-devel? To me your question sounds very legitimate!

**Comment by Nowosad** [comment]
Thanks @maelle for the suggestion. I just sent the email.

**Comment by maelle** [comment]
Good luck!
